### ISSUE TITLE
Is the help output correct?

### ISSUE THREAD

**Issue by ymkz** [azu/github-actions-badge#1]
`npx github-actions-badge --help`

output

```
  Generate GitHub Actions badge Markdown code.

  Usage
    $ migrate-hatenabookmark-to-asocial-bookmark --hatena <user-name>

  Options
    --hatena Hatena User name

  Examples
    $ migrate-hatenabookmark-to-asocial-bookmark --hatena test
```

ref: https://github.com/azu/github-actions-badge/blob/master/src/cli.ts#L4-L21

I think the [README Usage](https://github.com/azu/github-actions-badge#usage) is correct.

Thank you.

**Comment by azu** [comment]
Thanks for report!

fix it in https://github.com/azu/github-actions-badge/releases/tag/1.0.2
