### ISSUE TITLE
Query should be quote

### ISSUE THREAD

**Issue by znz** [azu/github-actions-badge#2]
`npx github-actions-badge` outputs on working copy of <https://github.com/ruby/actions>:

```
npx: 69個のパッケージを2.564秒でインストールしました。
[![Actions Status](https://github.com/ruby/actions/workflows/coverage/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3Acoverage)
[![Actions Status](https://github.com/ruby/actions/workflows/doxygen/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3Adoxygen)
[![Actions Status](https://github.com/ruby/actions/workflows/Make%20draft%20release%20package/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3AMake%20draft%20release%20package)
[![Actions Status](https://github.com/ruby/actions/workflows/Remove%20pub%2Ftmp%2Fruby-*/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3ARemove%20pub%2Ftmp%2Fruby-*)
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-master/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3Asnapshot-master)
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-ruby_2_4/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3Asnapshot-ruby_2_4)
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-ruby_2_5/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3Asnapshot-ruby_2_5)
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-ruby_2_6/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3Asnapshot-ruby_2_6)
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3Asnapshot)
[![Actions Status](https://github.com/ruby/actions/workflows/stable-snapshot/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3Astable-snapshot)
[![Actions Status](https://github.com/ruby/actions/workflows/update_index/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3Aupdate_index)
```

But query of `https://github.com/ruby/actions/actions?query=workflow%3AMake%20draft%20release%20package` is `workflow:Make` only.
It should be `https://github.com/ruby/actions/actions?query=workflow%3A%22Make+draft+release+package%22`.

**Comment by azu** [comment]
Thanks for report!

https://github.com/azu/github-actions-badge/releases/tag/1.0.3 will fix this issue.

1.0.3 Results:

```
npx github-actions-badge
npx: 69個のパッケージを12.497秒でインストールしました。
[![Actions Status](https://github.com/ruby/actions/workflows/coverage/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"coverage")
[![Actions Status](https://github.com/ruby/actions/workflows/doxygen/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"doxygen")
[![Actions Status](https://github.com/ruby/actions/workflows/Make%20draft%20release%20package/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"Make+draft+release+package")
[![Actions Status](https://github.com/ruby/actions/workflows/Remove%20pub%2Ftmp%2Fruby-*/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"Remove+pub/tmp/ruby-*")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-master/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot-master")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-ruby_2_4/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot-ruby_2_4")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-ruby_2_5/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot-ruby_2_5")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-ruby_2_6/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot-ruby_2_6")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot")
[![Actions Status](https://github.com/ruby/actions/workflows/stable-snapshot/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"stable-snapshot")
[![Actions Status](https://github.com/ruby/actions/workflows/update_index/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"update_index")
```

[![Actions Status](https://github.com/ruby/actions/workflows/coverage/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"coverage")
[![Actions Status](https://github.com/ruby/actions/workflows/doxygen/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"doxygen")
[![Actions Status](https://github.com/ruby/actions/workflows/Make%20draft%20release%20package/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"Make+draft+release+package")
[![Actions Status](https://github.com/ruby/actions/workflows/Remove%20pub%2Ftmp%2Fruby-*/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"Remove+pub/tmp/ruby-*")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-master/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot-master")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-ruby_2_4/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot-ruby_2_4")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-ruby_2_5/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot-ruby_2_5")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot-ruby_2_6/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot-ruby_2_6")
[![Actions Status](https://github.com/ruby/actions/workflows/snapshot/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"snapshot")
[![Actions Status](https://github.com/ruby/actions/workflows/stable-snapshot/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"stable-snapshot")
[![Actions Status](https://github.com/ruby/actions/workflows/update_index/badge.svg)](https://github.com/ruby/actions/actions?query=workflow%3A"update_index")
